# Generated by Django 5.2.3 on 2025-06-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='parkingLocation',
            fields=[
                ('locationID', models.AutoField(primary_key=True, serialize=False)),
                ('locationName', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'parkingLocation',
            },
        ),
        migrations.DeleteModel(
            name='userTable',
        ),
    ]
