# Generated by Django 5.2.3 on 2025-06-14 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_parkinglocation_delete_usertable'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('customerID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='parkingSpot',
            fields=[
                ('spotID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('occupied', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer')),
            ],
            options={
                'db_table': 'parkingSpot',
            },
        ),
        migrations.CreateModel(
            name='reserveTable',
            fields=[
                ('reserveID', models.AutoField(primary_key=True, serialize=False)),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer')),
                ('spotID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.parkingspot')),
            ],
            options={
                'db_table': 'reserveTable',
            },
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='reserveStatus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.reservetable'),
        ),
    ]
