# Generated by Django 5.2.3 on 2025-06-15 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customer_parkingspot_reservetable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspot',
            name='occupied',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.customer'),
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='reserveStatus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.reservetable'),
        ),
    ]
