# Generated by Django 5.2.3 on 2025-06-15 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_parkingspot_occupied_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspot',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.parkinglocation'),
        ),
    ]
