# Generated by Django 5.2.3 on 2025-06-16 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_reservetable_date_in_reservetable_date_out_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingspot',
            name='date_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parkingspot',
            name='date_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reservetable',
            name='date_in',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reservetable',
            name='date_out',
            field=models.DateTimeField(),
        ),
    ]
