# Generated by Django 5.2.3 on 2025-06-16 03:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_parkingspot_date_in_parkingspot_date_out_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingspot',
            name='date_in',
        ),
        migrations.RemoveField(
            model_name='parkingspot',
            name='date_out',
        ),
        migrations.AlterField(
            model_name='reservetable',
            name='customerID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservetable',
            name='spotID',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='core.parkingspot'),
        ),
        migrations.CreateModel(
            name='approvedreserveTable',
            fields=[
                ('approvedreserveID', models.AutoField(primary_key=True, serialize=False)),
                ('date_in', models.DateTimeField()),
                ('date_out', models.DateTimeField()),
                ('customerID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('spotID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.parkingspot')),
            ],
            options={
                'db_table': 'approvedreserveTable',
            },
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='occupied',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.approvedreservetable'),
        ),
    ]
