# Generated by Django 5.2.3 on 2025-06-16 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_parkingspot_date_in_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingspot',
            name='occupied',
        ),
    ]
